##**DATA PREPARATION**

Com a estruturação do sistema de monitoramento concluída, foi possível captar dados provenientes da aplicação alvo, e armazená-los num banco de dados para uso futuro. Nesta etapa os valores coletados foram ajustados em seu *type* para a utilização dos mesmos pelo modelo. Também foi ajustado o valor do campo '*available*'.

In [4]:
from matplotlib import pyplot as plt
import pandas as pd

In [5]:
df = pd.read_csv('metrics_7.csv')
df.head()

,_id,available,cpu_usage,heap_used,memory_used,non_heap_used,time,time_response_get,time_response_post
0,627cefdbf7301dd01a1e36b2,1,0.0,0.0,0.0,0.0,1.652355e+09,0.0,0.0
1,627cefe7f7301dd01a1e36b3,1,0.0,0.0,0.0,0.0,1.652355e+09,0.0,0.0
2,628f5f6b52016e4226c5a3da,1,0.0,0.0,0.0,0.0,1.653563e+09,0.0,0.0
3,628f5ffd9dc9c74e6963bf69,1,0.0,0.0,0.0,0.0,1.653563e+09,0.0,0.0
4,628f60089dc9c74e6963bf6a,1,0.0,0.0,0.0,0.0,1.653563e+09,0.0,0.0

In [6]:
cols = ['time_response_get',
'time_response_post',
'memory_used',
'heap_used',
'non_heap_used',
'cpu_usage']

df = df.fillna(0)
df = df.astype({'time_response_get': float, 
                'time_response_post': float, 
                'cpu_usage': float, 
                'available': float, 
                'memory_used': float, 
                'heap_used': float, 
                'non_heap_used': float
                })

i = 0
while i < len(df['time_response_get']):
  col_values = []
  for column in cols:
    if df[column][i] != 0:
      col_values.append(df[column][i])
  if len(col_values) == 0:
    df['available'][i] = 0
  else:
    df['available'][i] = 1
  i = i + 1

df['available'].unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([0., 1.])